// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Post {
    public var save: Save {
        Save(path: path + "/save")
    }

    public struct Save {
        /// Path: `/post/save`
        public let path: String

        public func post(_ body: LemmyKit.SavePost? = nil) -> Request<LemmyKit.PostResponse> {
            Request(path: path, method: "POST", body: body)
        }
    }
}
