// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Comment {
    public var save: Save {
        Save(path: path + "/save")
    }

    public struct Save {
        /// Path: `/comment/save`
        public let path: String

        public func post(_ body: LemmyKit.SaveComment? = nil) -> Request<LemmyKit.CommentResponse> {
            Request(path: path, method: "POST", body: body)
        }
    }
}
