// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    public static var admin: Admin {
        Admin(path: "/admin")
    }

    public struct Admin {
        /// Path: `/admin`
        public let path: String
    }
}
