// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Admin.RegistrationApplication {
    public var approve: Approve {
        Approve(path: path + "/approve")
    }

    public struct Approve {
        /// Path: `/admin/registration_application/approve`
        public let path: String

        public func put(_ body: LemmyKit.ApproveRegistrationApplication? = nil) -> Request<LemmyKit.RegistrationApplicationView> {
            Request(path: path, method: "PUT", body: body)
        }
    }
}
