// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.User {
    public var saveUserSettings: SaveUserSettings {
        SaveUserSettings(path: path + "/save_user_settings")
    }

    public struct SaveUserSettings {
        /// Path: `/user/save_user_settings`
        public let path: String

        public func put(_ body: LemmyKit.SaveUserSettings? = nil) -> Request<LemmyKit.LoginResponse> {
            Request(path: path, method: "PUT", body: body)
        }
    }
}
