// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.User {
    public var getCaptcha: GetCaptcha {
        GetCaptcha(path: path + "/get_captcha")
    }

    public struct GetCaptcha {
        /// Path: `/user/get_captcha`
        public let path: String

        public func get(getCaptcha: GetCaptcha? = nil) -> Request<LemmyKit.GetCaptchaResponse> {
            Request(path: path, method: "GET", query: makeGetQuery(getCaptcha))
        }

        private func makeGetQuery(_ getCaptcha: GetCaptcha?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(getCaptcha, forKey: "GetCaptcha")
            return encoder.items
        }

        public struct GetCaptcha: Codable {
            /// GetCaptcha.auth
            public var auth: String?

            public init(auth: String? = nil) {
                self.auth = auth
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(auth, forKey: "auth")
                return encoder.items
            }
        }
    }
}
