// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.User {
    public var deleteAccount: DeleteAccount {
        DeleteAccount(path: path + "/delete_account")
    }

    public struct DeleteAccount {
        /// Path: `/user/delete_account`
        public let path: String

        public func post(_ body: LemmyKit.DeleteAccount? = nil) -> Request<Void> {
            Request(path: path, method: "POST", body: body)
        }
    }
}
