// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Post {
    public var feature: Feature {
        Feature(path: path + "/feature")
    }

    public struct Feature {
        /// Path: `/post/feature`
        public let path: String

        public func post(_ body: LemmyKit.FeaturePost? = nil) -> Request<LemmyKit.PostResponse> {
            Request(path: path, method: "POST", body: body)
        }
    }
}
