// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.User {
    public var changePassword: ChangePassword {
        ChangePassword(path: path + "/change_password")
    }

    public struct ChangePassword {
        /// Path: `/user/change_password`
        public let path: String

        public func put(_ body: LemmyKit.ChangePassword? = nil) -> Request<LemmyKit.LoginResponse> {
            Request(path: path, method: "PUT", body: body)
        }
    }
}
