// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.User {
    public var passwordReset: PasswordReset {
        PasswordReset(path: path + "/password_reset")
    }

    public struct PasswordReset {
        /// Path: `/user/password_reset`
        public let path: String

        public func post(_ body: LemmyKit.PasswordReset? = nil) -> Request<Void> {
            Request(path: path, method: "POST", body: body)
        }
    }
}
