// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Post {
    public var list: List {
        List(path: path + "/list")
    }

    public struct List {
        /// Path: `/post/list`
        public let path: String

        public func get(listPosts: ListPosts? = nil) -> Request<LemmyKit.GetPostsResponse> {
            Request(path: path, method: "GET", query: makeGetQuery(listPosts))
        }

        private func makeGetQuery(_ listPosts: ListPosts?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(listPosts, forKey: "ListPosts")
            return encoder.items
        }

        /// GetPosts
        public struct ListPosts: Codable {
            /// ListingType
            public var type: `Type`?
            /// SortType
            public var sort: Sort?
            /// GetPosts.page
            public var page: Double?
            /// GetPosts.limit
            public var limit: Double?
            public var communityID: Double?
            /// GetPosts.community_name
            public var communityName: String?
            /// GetPosts.saved_only
            public var isSavedOnly: Bool?
            /// GetPosts.moderator_view
            public var isModeratorView: Bool?
            /// GetPosts.auth
            public var auth: String?

            /// ListingType
            public enum `Type`: String, Codable, CaseIterable {
                case all = "All"
                case local = "Local"
                case subscribed = "Subscribed"
            }

            /// SortType
            public enum Sort: String, Codable, CaseIterable {
                case active = "Active"
                case hot = "Hot"
                case new = "New"
                case old = "Old"
                case topDay = "TopDay"
                case topWeek = "TopWeek"
                case topMonth = "TopMonth"
                case topYear = "TopYear"
                case topAll = "TopAll"
                case mostComments = "MostComments"
                case newComments = "NewComments"
                case topHour = "TopHour"
                case topSixHour = "TopSixHour"
                case topTwelveHour = "TopTwelveHour"
                case topThreeMonths = "TopThreeMonths"
                case topSixMonths = "TopSixMonths"
                case topNineMonths = "TopNineMonths"
            }

            public init(type: `Type`? = nil, sort: Sort? = nil, page: Double? = nil, limit: Double? = nil, communityID: Double? = nil, communityName: String? = nil, isSavedOnly: Bool? = nil, isModeratorView: Bool? = nil, auth: String? = nil) {
                self.type = type
                self.sort = sort
                self.page = page
                self.limit = limit
                self.communityID = communityID
                self.communityName = communityName
                self.isSavedOnly = isSavedOnly
                self.isModeratorView = isModeratorView
                self.auth = auth
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(type, forKey: "type_")
                encoder.encode(sort, forKey: "sort")
                encoder.encode(page, forKey: "page")
                encoder.encode(limit, forKey: "limit")
                encoder.encode(communityID, forKey: "community_id")
                encoder.encode(communityName, forKey: "community_name")
                encoder.encode(isSavedOnly, forKey: "saved_only")
                encoder.encode(isModeratorView, forKey: "moderator_view")
                encoder.encode(auth, forKey: "auth")
                return encoder.items
            }
        }
    }
}
