// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Community {
    public var mod: Mod {
        Mod(path: path + "/mod")
    }

    public struct Mod {
        /// Path: `/community/mod`
        public let path: String

        public func post(_ body: LemmyKit.AddModToCommunity? = nil) -> Request<LemmyKit.AddModToCommunityResponse> {
            Request(path: path, method: "POST", body: body)
        }
    }
}
