// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    public static var customEmoji: CustomEmoji {
        CustomEmoji(path: "/custom_emoji")
    }

    public struct CustomEmoji {
        /// Path: `/custom_emoji`
        public let path: String

        public func post(_ body: LemmyKit.CreateCustomEmoji? = nil) -> Request<LemmyKit.CustomEmojiResponse> {
            Request(path: path, method: "POST", body: body)
        }

        public func put(_ body: LemmyKit.EditCustomEmoji? = nil) -> Request<LemmyKit.CustomEmojiResponse> {
            Request(path: path, method: "PUT", body: body)
        }
    }
}
