// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Admin {
    public var add: Add {
        Add(path: path + "/add")
    }

    public struct Add {
        /// Path: `/admin/add`
        public let path: String

        public func post(_ body: LemmyKit.AddAdmin? = nil) -> Request<LemmyKit.AddAdminResponse> {
            Request(path: path, method: "POST", body: body)
        }
    }
}
