// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Community {
    public var banUser: BanUser {
        BanUser(path: path + "/ban_user")
    }

    public struct BanUser {
        /// Path: `/community/ban_user`
        public let path: String

        public func post(_ body: LemmyKit.BanFromCommunity? = nil) -> Request<LemmyKit.BanFromCommunityResponse> {
            Request(path: path, method: "POST", body: body)
        }
    }
}
