// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.User {
    public var login: Login {
        Login(path: path + "/login")
    }

    public struct Login {
        /// Path: `/user/login`
        public let path: String

        public func post(_ body: LemmyKit.Login? = nil) -> Request<LemmyKit.LoginResponse> {
            Request(path: path, method: "POST", body: body)
        }
    }
}
