// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Admin {
    public var purge: Purge {
        Purge(path: path + "/purge")
    }

    public struct Purge {
        /// Path: `/admin/purge`
        public let path: String
    }
}
