// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Admin.RegistrationApplication {
    public var list: List {
        List(path: path + "/list")
    }

    public struct List {
        /// Path: `/admin/registration_application/list`
        public let path: String

        public func get(listRegistrationApplications: ListRegistrationApplications? = nil) -> Request<LemmyKit.ListRegistrationApplicationsResponse> {
            Request(path: path, method: "GET", query: makeGetQuery(listRegistrationApplications))
        }

        private func makeGetQuery(_ listRegistrationApplications: ListRegistrationApplications?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(listRegistrationApplications, forKey: "ListRegistrationApplications")
            return encoder.items
        }

        public struct ListRegistrationApplications: Codable {
            /// ListRegistrationApplications.unread_only
            public var isUnreadOnly: Bool?
            /// ListRegistrationApplications.page
            public var page: Double?
            /// ListRegistrationApplications.limit
            public var limit: Double?
            /// ListRegistrationApplications.auth
            public var auth: String

            public init(isUnreadOnly: Bool? = nil, page: Double? = nil, limit: Double? = nil, auth: String) {
                self.isUnreadOnly = isUnreadOnly
                self.page = page
                self.limit = limit
                self.auth = auth
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(isUnreadOnly, forKey: "unread_only")
                encoder.encode(page, forKey: "page")
                encoder.encode(limit, forKey: "limit")
                encoder.encode(auth, forKey: "auth")
                return encoder.items
            }
        }
    }
}
