// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    public static var privateMessage: PrivateMessage {
        PrivateMessage(path: "/private_message")
    }

    public struct PrivateMessage {
        /// Path: `/private_message`
        public let path: String

        public func post(_ body: LemmyKit.CreatePrivateMessage? = nil) -> Request<LemmyKit.PrivateMessageResponse> {
            Request(path: path, method: "POST", body: body)
        }

        public func put(_ body: LemmyKit.EditPrivateMessage? = nil) -> Request<LemmyKit.PrivateMessageResponse> {
            Request(path: path, method: "PUT", body: body)
        }
    }
}
