// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Comment {
    public var distinguish: Distinguish {
        Distinguish(path: path + "/distinguish")
    }

    public struct Distinguish {
        /// Path: `/comment/distinguish`
        public let path: String

        public func post(_ body: LemmyKit.DistinguishComment? = nil) -> Request<LemmyKit.CommentResponse> {
            Request(path: path, method: "POST", body: body)
        }
    }
}
