// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.User {
    public var markAllAsRead: MarkAllAsRead {
        MarkAllAsRead(path: path + "/mark_all_as_read")
    }

    public struct MarkAllAsRead {
        /// Path: `/user/mark_all_as_read`
        public let path: String

        public func post(_ body: LemmyKit.MarkAllAsRead? = nil) -> Request<LemmyKit.GetRepliesResponse> {
            Request(path: path, method: "POST", body: body)
        }
    }
}
