// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.CustomEmoji {
    public var delete: Delete {
        Delete(path: path + "/delete")
    }

    public struct Delete {
        /// Path: `/custom_emoji/delete`
        public let path: String

        public func post(_ body: LemmyKit.DeleteCustomEmoji? = nil) -> Request<LemmyKit.DeleteCustomEmojiResponse> {
            Request(path: path, method: "POST", body: body)
        }
    }
}
