// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Post {
    public var report: Report {
        Report(path: path + "/report")
    }

    public struct Report {
        /// Path: `/post/report`
        public let path: String

        public func post(_ body: LemmyKit.CreatePostReport? = nil) -> Request<LemmyKit.PostReportResponse> {
            Request(path: path, method: "POST", body: body)
        }
    }
}
