// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.PrivateMessage {
    public var list: List {
        List(path: path + "/list")
    }

    public struct List {
        /// Path: `/private_message/list`
        public let path: String

        public func get(getPrivateMessages: GetPrivateMessages? = nil) -> Request<LemmyKit.PrivateMessagesResponse> {
            Request(path: path, method: "GET", query: makeGetQuery(getPrivateMessages))
        }

        private func makeGetQuery(_ getPrivateMessages: GetPrivateMessages?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(getPrivateMessages, forKey: "GetPrivateMessages")
            return encoder.items
        }

        public struct GetPrivateMessages: Codable {
            /// GetPrivateMessages.unread_only
            public var isUnreadOnly: Bool?
            /// GetPrivateMessages.page
            public var page: Double?
            /// GetPrivateMessages.limit
            public var limit: Double?
            /// GetPrivateMessages.auth
            public var auth: String

            public init(isUnreadOnly: Bool? = nil, page: Double? = nil, limit: Double? = nil, auth: String) {
                self.isUnreadOnly = isUnreadOnly
                self.page = page
                self.limit = limit
                self.auth = auth
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(isUnreadOnly, forKey: "unread_only")
                encoder.encode(page, forKey: "page")
                encoder.encode(limit, forKey: "limit")
                encoder.encode(auth, forKey: "auth")
                return encoder.items
            }
        }
    }
}
