// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Admin.Purge {
    public var person: Person {
        Person(path: path + "/person")
    }

    public struct Person {
        /// Path: `/admin/purge/person`
        public let path: String

        public func post(_ body: LemmyKit.PurgePerson? = nil) -> Request<LemmyKit.PurgeItemResponse> {
            Request(path: path, method: "POST", body: body)
        }
    }
}
