// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Community {
    public var hide: Hide {
        Hide(path: path + "/hide")
    }

    public struct Hide {
        /// Path: `/community/hide`
        public let path: String

        public func put(_ body: LemmyKit.HideCommunity? = nil) -> Request<Void> {
            Request(path: path, method: "PUT", body: body)
        }
    }
}
