// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Post.Report {
    public var resolve: Resolve {
        Resolve(path: path + "/resolve")
    }

    public struct Resolve {
        /// Path: `/post/report/resolve`
        public let path: String

        public func put(_ body: LemmyKit.ResolvePostReport? = nil) -> Request<LemmyKit.PostReportResponse> {
            Request(path: path, method: "PUT", body: body)
        }
    }
}
