// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Admin.Purge {
    public var post: Post {
        Post(path: path + "/post")
    }

    public struct Post {
        /// Path: `/admin/purge/post`
        public let path: String

        public func post(_ body: LemmyKit.PurgePost? = nil) -> Request<LemmyKit.PurgeItemResponse> {
            Request(path: path, method: "POST", body: body)
        }
    }
}
