// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.User {
    public var leaveAdmin: LeaveAdmin {
        LeaveAdmin(path: path + "/leave_admin")
    }

    public struct LeaveAdmin {
        /// Path: `/user/leave_admin`
        public let path: String

        public func post(_ body: LemmyKit.LeaveAdmin? = nil) -> Request<LemmyKit.GetSiteResponse> {
            Request(path: path, method: "POST", body: body)
        }
    }
}
