// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct AddAdminResponse: Codable {
    /// AddAdminResponse.admins
    public var admins: [PersonView]

    public init(admins: [PersonView]) {
        self.admins = admins
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.admins = try values.decode([PersonView].self, forKey: "admins")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(admins, forKey: "admins")
    }
}
