// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct AdminPurgePostView: Codable {
    public var adminPurgePost: AdminPurgePost
    /// Person
    public var admin: Person?
    public var community: Community

    public init(adminPurgePost: AdminPurgePost, admin: Person? = nil, community: Community) {
        self.adminPurgePost = adminPurgePost
        self.admin = admin
        self.community = community
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.adminPurgePost = try values.decode(AdminPurgePost.self, forKey: "admin_purge_post")
        self.admin = try values.decodeIfPresent(Person.self, forKey: "admin")
        self.community = try values.decode(Community.self, forKey: "community")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(adminPurgePost, forKey: "admin_purge_post")
        try values.encodeIfPresent(admin, forKey: "admin")
        try values.encode(community, forKey: "community")
    }
}
