// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct AdminPurgeCommunityView: Codable {
    public var adminPurgeCommunity: AdminPurgeCommunity
    /// Person
    public var admin: Person?

    public init(adminPurgeCommunity: AdminPurgeCommunity, admin: Person? = nil) {
        self.adminPurgeCommunity = adminPurgeCommunity
        self.admin = admin
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.adminPurgeCommunity = try values.decode(AdminPurgeCommunity.self, forKey: "admin_purge_community")
        self.admin = try values.decodeIfPresent(Person.self, forKey: "admin")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(adminPurgeCommunity, forKey: "admin_purge_community")
        try values.encodeIfPresent(admin, forKey: "admin")
    }
}
