// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct AdminPurgePersonView: Codable {
    public var adminPurgePerson: AdminPurgePerson
    /// Person
    public var admin: Person?

    public init(adminPurgePerson: AdminPurgePerson, admin: Person? = nil) {
        self.adminPurgePerson = adminPurgePerson
        self.admin = admin
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.adminPurgePerson = try values.decode(AdminPurgePerson.self, forKey: "admin_purge_person")
        self.admin = try values.decodeIfPresent(Person.self, forKey: "admin")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(adminPurgePerson, forKey: "admin_purge_person")
        try values.encodeIfPresent(admin, forKey: "admin")
    }
}
