// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct BanFromCommunityResponse: Codable {
    public var personView: PersonView
    /// BanFromCommunityResponse.banned
    public var isBanned: Bool

    public init(personView: PersonView, isBanned: Bool) {
        self.personView = personView
        self.isBanned = isBanned
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.personView = try values.decode(PersonView.self, forKey: "person_view")
        self.isBanned = try values.decode(Bool.self, forKey: "banned")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(personView, forKey: "person_view")
        try values.encode(isBanned, forKey: "banned")
    }
}
