// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct BannedPersonsResponse: Codable {
    /// BannedPersonsResponse.banned
    public var banned: [PersonView]

    public init(banned: [PersonView]) {
        self.banned = banned
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.banned = try values.decode([PersonView].self, forKey: "banned")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(banned, forKey: "banned")
    }
}
