// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct BlockCommunity: Codable {
    public var communityID: Double
    /// BlockCommunity.block
    public var isBlock: Bool
    /// BlockCommunity.auth
    public var auth: String

    public init(communityID: Double, isBlock: Bool, auth: String) {
        self.communityID = communityID
        self.isBlock = isBlock
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.communityID = try values.decode(Double.self, forKey: "community_id")
        self.isBlock = try values.decode(Bool.self, forKey: "block")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(communityID, forKey: "community_id")
        try values.encode(isBlock, forKey: "block")
        try values.encode(auth, forKey: "auth")
    }
}
