// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct BlockPerson: Codable {
    public var personID: Double
    /// BlockPerson.block
    public var isBlock: Bool
    /// BlockPerson.auth
    public var auth: String

    public init(personID: Double, isBlock: Bool, auth: String) {
        self.personID = personID
        self.isBlock = isBlock
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.personID = try values.decode(Double.self, forKey: "person_id")
        self.isBlock = try values.decode(Bool.self, forKey: "block")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(personID, forKey: "person_id")
        try values.encode(isBlock, forKey: "block")
        try values.encode(auth, forKey: "auth")
    }
}
