// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct BlockCommunityResponse: Codable {
    public var communityView: CommunityView
    /// BlockCommunityResponse.blocked
    public var isBlocked: Bool

    public init(communityView: CommunityView, isBlocked: Bool) {
        self.communityView = communityView
        self.isBlocked = isBlocked
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.communityView = try values.decode(CommunityView.self, forKey: "community_view")
        self.isBlocked = try values.decode(Bool.self, forKey: "blocked")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(communityView, forKey: "community_view")
        try values.encode(isBlocked, forKey: "blocked")
    }
}
