// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct BlockPersonResponse: Codable {
    public var personView: PersonView
    /// BlockPersonResponse.blocked
    public var isBlocked: Bool

    public init(personView: PersonView, isBlocked: Bool) {
        self.personView = personView
        self.isBlocked = isBlocked
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.personView = try values.decode(PersonView.self, forKey: "person_view")
        self.isBlocked = try values.decode(Bool.self, forKey: "blocked")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(personView, forKey: "person_view")
        try values.encode(isBlocked, forKey: "blocked")
    }
}
