// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CaptchaResponse: Codable {
    /// CaptchaResponse.png
    public var png: String
    /// CaptchaResponse.wav
    public var wav: String
    /// CaptchaResponse.uuid
    public var uuid: String

    public init(png: String, wav: String, uuid: String) {
        self.png = png
        self.wav = wav
        self.uuid = uuid
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.png = try values.decode(String.self, forKey: "png")
        self.wav = try values.decode(String.self, forKey: "wav")
        self.uuid = try values.decode(String.self, forKey: "uuid")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(png, forKey: "png")
        try values.encode(wav, forKey: "wav")
        try values.encode(uuid, forKey: "uuid")
    }
}
