// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ChangePassword: Codable {
    /// ChangePassword.new_password
    public var newPassword: String
    /// ChangePassword.new_password_verify
    public var newPasswordVerify: String
    /// ChangePassword.old_password
    public var oldPassword: String
    /// ChangePassword.auth
    public var auth: String

    public init(newPassword: String, newPasswordVerify: String, oldPassword: String, auth: String) {
        self.newPassword = newPassword
        self.newPasswordVerify = newPasswordVerify
        self.oldPassword = oldPassword
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.newPassword = try values.decode(String.self, forKey: "new_password")
        self.newPasswordVerify = try values.decode(String.self, forKey: "new_password_verify")
        self.oldPassword = try values.decode(String.self, forKey: "old_password")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(newPassword, forKey: "new_password")
        try values.encode(newPasswordVerify, forKey: "new_password_verify")
        try values.encode(oldPassword, forKey: "old_password")
        try values.encode(auth, forKey: "auth")
    }
}
