// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CommentReportView: Codable {
    public var commentReport: CommentReport
    public var comment: Comment
    public var post: Post
    public var community: Community
    /// Person
    public var creator: Person
    /// Person
    public var commentCreator: Person
    /// CommentAggregates
    public var counts: CommentAggregates
    /// CommentReportView.creator_banned_from_community
    public var isCreatorBannedFromCommunity: Bool
    /// CommentReportView.my_vote
    public var myVote: Double?
    /// Person
    public var resolver: Person?

    public init(commentReport: CommentReport, comment: Comment, post: Post, community: Community, creator: Person, commentCreator: Person, counts: CommentAggregates, isCreatorBannedFromCommunity: Bool, myVote: Double? = nil, resolver: Person? = nil) {
        self.commentReport = commentReport
        self.comment = comment
        self.post = post
        self.community = community
        self.creator = creator
        self.commentCreator = commentCreator
        self.counts = counts
        self.isCreatorBannedFromCommunity = isCreatorBannedFromCommunity
        self.myVote = myVote
        self.resolver = resolver
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.commentReport = try values.decode(CommentReport.self, forKey: "comment_report")
        self.comment = try values.decode(Comment.self, forKey: "comment")
        self.post = try values.decode(Post.self, forKey: "post")
        self.community = try values.decode(Community.self, forKey: "community")
        self.creator = try values.decode(Person.self, forKey: "creator")
        self.commentCreator = try values.decode(Person.self, forKey: "comment_creator")
        self.counts = try values.decode(CommentAggregates.self, forKey: "counts")
        self.isCreatorBannedFromCommunity = try values.decode(Bool.self, forKey: "creator_banned_from_community")
        self.myVote = try values.decodeIfPresent(Double.self, forKey: "my_vote")
        self.resolver = try values.decodeIfPresent(Person.self, forKey: "resolver")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(commentReport, forKey: "comment_report")
        try values.encode(comment, forKey: "comment")
        try values.encode(post, forKey: "post")
        try values.encode(community, forKey: "community")
        try values.encode(creator, forKey: "creator")
        try values.encode(commentCreator, forKey: "comment_creator")
        try values.encode(counts, forKey: "counts")
        try values.encode(isCreatorBannedFromCommunity, forKey: "creator_banned_from_community")
        try values.encodeIfPresent(myVote, forKey: "my_vote")
        try values.encodeIfPresent(resolver, forKey: "resolver")
    }
}
