// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CommunityAggregates: Codable {
    /// CommunityAggregates.id
    public var id: Double
    public var communityID: Double
    /// CommunityAggregates.subscribers
    public var subscribers: Double
    /// CommunityAggregates.posts
    public var posts: Double
    /// CommunityAggregates.comments
    public var comments: Double
    /// CommunityAggregates.published
    public var published: String
    /// CommunityAggregates.users_active_day
    public var usersActiveDay: Double
    /// CommunityAggregates.users_active_week
    public var usersActiveWeek: Double
    /// CommunityAggregates.users_active_month
    public var usersActiveMonth: Double
    /// CommunityAggregates.users_active_half_year
    public var usersActiveHalfYear: Double
    /// CommunityAggregates.hot_rank
    public var hotRank: Double

    public init(id: Double, communityID: Double, subscribers: Double, posts: Double, comments: Double, published: String, usersActiveDay: Double, usersActiveWeek: Double, usersActiveMonth: Double, usersActiveHalfYear: Double, hotRank: Double) {
        self.id = id
        self.communityID = communityID
        self.subscribers = subscribers
        self.posts = posts
        self.comments = comments
        self.published = published
        self.usersActiveDay = usersActiveDay
        self.usersActiveWeek = usersActiveWeek
        self.usersActiveMonth = usersActiveMonth
        self.usersActiveHalfYear = usersActiveHalfYear
        self.hotRank = hotRank
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Double.self, forKey: "id")
        self.communityID = try values.decode(Double.self, forKey: "community_id")
        self.subscribers = try values.decode(Double.self, forKey: "subscribers")
        self.posts = try values.decode(Double.self, forKey: "posts")
        self.comments = try values.decode(Double.self, forKey: "comments")
        self.published = try values.decode(String.self, forKey: "published")
        self.usersActiveDay = try values.decode(Double.self, forKey: "users_active_day")
        self.usersActiveWeek = try values.decode(Double.self, forKey: "users_active_week")
        self.usersActiveMonth = try values.decode(Double.self, forKey: "users_active_month")
        self.usersActiveHalfYear = try values.decode(Double.self, forKey: "users_active_half_year")
        self.hotRank = try values.decode(Double.self, forKey: "hot_rank")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(communityID, forKey: "community_id")
        try values.encode(subscribers, forKey: "subscribers")
        try values.encode(posts, forKey: "posts")
        try values.encode(comments, forKey: "comments")
        try values.encode(published, forKey: "published")
        try values.encode(usersActiveDay, forKey: "users_active_day")
        try values.encode(usersActiveWeek, forKey: "users_active_week")
        try values.encode(usersActiveMonth, forKey: "users_active_month")
        try values.encode(usersActiveHalfYear, forKey: "users_active_half_year")
        try values.encode(hotRank, forKey: "hot_rank")
    }
}
