// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CommunityBlockView: Codable {
    public var person: Person
    public var community: Community

    public init(person: Person, community: Community) {
        self.person = person
        self.community = community
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.person = try values.decode(Person.self, forKey: "person")
        self.community = try values.decode(Community.self, forKey: "community")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(person, forKey: "person")
        try values.encode(community, forKey: "community")
    }
}
