// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CommentResponse: Codable {
    public var commentView: CommentView
    /// CommentResponse.recipient_ids
    public var recipientIDs: [Double]
    /// CommentResponse.form_id
    public var formID: String?

    public init(commentView: CommentView, recipientIDs: [Double], formID: String? = nil) {
        self.commentView = commentView
        self.recipientIDs = recipientIDs
        self.formID = formID
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.commentView = try values.decode(CommentView.self, forKey: "comment_view")
        self.recipientIDs = try values.decode([Double].self, forKey: "recipient_ids")
        self.formID = try values.decodeIfPresent(String.self, forKey: "form_id")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(commentView, forKey: "comment_view")
        try values.encode(recipientIDs, forKey: "recipient_ids")
        try values.encodeIfPresent(formID, forKey: "form_id")
    }
}
