// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CommentReplyResponse: Codable {
    public var commentReplyView: CommentReplyView

    public init(commentReplyView: CommentReplyView) {
        self.commentReplyView = commentReplyView
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.commentReplyView = try values.decode(CommentReplyView.self, forKey: "comment_reply_view")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(commentReplyView, forKey: "comment_reply_view")
    }
}
