// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CommunityView: Codable {
    public var community: Community
    /// SubscribedType
    public var subscribed: SubscribedType
    /// CommunityView.blocked
    public var isBlocked: Bool
    /// CommunityAggregates
    public var counts: CommunityAggregates

    public init(community: Community, subscribed: SubscribedType, isBlocked: Bool, counts: CommunityAggregates) {
        self.community = community
        self.subscribed = subscribed
        self.isBlocked = isBlocked
        self.counts = counts
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.community = try values.decode(Community.self, forKey: "community")
        self.subscribed = try values.decode(SubscribedType.self, forKey: "subscribed")
        self.isBlocked = try values.decode(Bool.self, forKey: "blocked")
        self.counts = try values.decode(CommunityAggregates.self, forKey: "counts")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(community, forKey: "community")
        try values.encode(subscribed, forKey: "subscribed")
        try values.encode(isBlocked, forKey: "blocked")
        try values.encode(counts, forKey: "counts")
    }
}
