// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CommentReportResponse: Codable {
    public var commentReportView: CommentReportView

    public init(commentReportView: CommentReportView) {
        self.commentReportView = commentReportView
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.commentReportView = try values.decode(CommentReportView.self, forKey: "comment_report_view")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(commentReportView, forKey: "comment_report_view")
    }
}
