// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CommunityResponse: Codable {
    public var communityView: CommunityView
    /// CommunityResponse.discussion_languages
    public var discussionLanguages: [Double]

    public init(communityView: CommunityView, discussionLanguages: [Double]) {
        self.communityView = communityView
        self.discussionLanguages = discussionLanguages
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.communityView = try values.decode(CommunityView.self, forKey: "community_view")
        self.discussionLanguages = try values.decode([Double].self, forKey: "discussion_languages")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(communityView, forKey: "community_view")
        try values.encode(discussionLanguages, forKey: "discussion_languages")
    }
}
