// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CommunityModeratorView: Codable {
    public var community: Community
    /// Person
    public var moderator: Person

    public init(community: Community, moderator: Person) {
        self.community = community
        self.moderator = moderator
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.community = try values.decode(Community.self, forKey: "community")
        self.moderator = try values.decode(Person.self, forKey: "moderator")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(community, forKey: "community")
        try values.encode(moderator, forKey: "moderator")
    }
}
