// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CommentReply: Codable {
    /// CommentReplyId
    public var id: Double
    /// PersonId
    public var recipientID: Double
    public var commentID: Double
    /// CommentReply.read
    public var isRead: Bool
    /// CommentReply.published
    public var published: String

    public init(id: Double, recipientID: Double, commentID: Double, isRead: Bool, published: String) {
        self.id = id
        self.recipientID = recipientID
        self.commentID = commentID
        self.isRead = isRead
        self.published = published
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Double.self, forKey: "id")
        self.recipientID = try values.decode(Double.self, forKey: "recipient_id")
        self.commentID = try values.decode(Double.self, forKey: "comment_id")
        self.isRead = try values.decode(Bool.self, forKey: "read")
        self.published = try values.decode(String.self, forKey: "published")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(recipientID, forKey: "recipient_id")
        try values.encode(commentID, forKey: "comment_id")
        try values.encode(isRead, forKey: "read")
        try values.encode(published, forKey: "published")
    }
}
