// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public enum CommentSortType: String, Codable, CaseIterable {
    case hot = "Hot"
    case top = "Top"
    case new = "New"
    case old = "Old"
}
