// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CreatePostReport: Codable {
    public var postID: Double
    /// CreatePostReport.reason
    public var reason: String
    /// CreatePostReport.auth
    public var auth: String

    public init(postID: Double, reason: String, auth: String) {
        self.postID = postID
        self.reason = reason
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.postID = try values.decode(Double.self, forKey: "post_id")
        self.reason = try values.decode(String.self, forKey: "reason")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(postID, forKey: "post_id")
        try values.encode(reason, forKey: "reason")
        try values.encode(auth, forKey: "auth")
    }
}
