// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CreateCommentReport: Codable {
    public var commentID: Double
    /// CreateCommentReport.reason
    public var reason: String
    /// CreateCommentReport.auth
    public var auth: String

    public init(commentID: Double, reason: String, auth: String) {
        self.commentID = commentID
        self.reason = reason
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.commentID = try values.decode(Double.self, forKey: "comment_id")
        self.reason = try values.decode(String.self, forKey: "reason")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(commentID, forKey: "comment_id")
        try values.encode(reason, forKey: "reason")
        try values.encode(auth, forKey: "auth")
    }
}
