// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CreatePrivateMessageReport: Codable {
    public var privateMessageID: Double
    /// CreatePrivateMessageReport.reason
    public var reason: String
    /// CreatePrivateMessageReport.auth
    public var auth: String

    public init(privateMessageID: Double, reason: String, auth: String) {
        self.privateMessageID = privateMessageID
        self.reason = reason
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.privateMessageID = try values.decode(Double.self, forKey: "private_message_id")
        self.reason = try values.decode(String.self, forKey: "reason")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(privateMessageID, forKey: "private_message_id")
        try values.encode(reason, forKey: "reason")
        try values.encode(auth, forKey: "auth")
    }
}
