// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CustomEmojiView: Codable {
    public var customEmoji: CustomEmoji
    /// CustomEmojiView.keywords
    public var keywords: [CustomEmojiKeyword]

    public init(customEmoji: CustomEmoji, keywords: [CustomEmojiKeyword]) {
        self.customEmoji = customEmoji
        self.keywords = keywords
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.customEmoji = try values.decode(CustomEmoji.self, forKey: "custom_emoji")
        self.keywords = try values.decode([CustomEmojiKeyword].self, forKey: "keywords")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(customEmoji, forKey: "custom_emoji")
        try values.encode(keywords, forKey: "keywords")
    }
}
