// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CustomEmojiResponse: Codable {
    /// CustomEmojiView
    public var customEmoji: CustomEmojiView

    public init(customEmoji: CustomEmojiView) {
        self.customEmoji = customEmoji
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.customEmoji = try values.decode(CustomEmojiView.self, forKey: "custom_emoji")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(customEmoji, forKey: "custom_emoji")
    }
}
