// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct DeletePost: Codable {
    public var postID: Double
    /// DeletePost.deleted
    public var isDeleted: Bool
    /// DeletePost.auth
    public var auth: String

    public init(postID: Double, isDeleted: Bool, auth: String) {
        self.postID = postID
        self.isDeleted = isDeleted
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.postID = try values.decode(Double.self, forKey: "post_id")
        self.isDeleted = try values.decode(Bool.self, forKey: "deleted")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(postID, forKey: "post_id")
        try values.encode(isDeleted, forKey: "deleted")
        try values.encode(auth, forKey: "auth")
    }
}
