// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct DeleteComment: Codable {
    public var commentID: Double
    /// DeleteComment.deleted
    public var isDeleted: Bool
    /// DeleteComment.auth
    public var auth: String

    public init(commentID: Double, isDeleted: Bool, auth: String) {
        self.commentID = commentID
        self.isDeleted = isDeleted
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.commentID = try values.decode(Double.self, forKey: "comment_id")
        self.isDeleted = try values.decode(Bool.self, forKey: "deleted")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(commentID, forKey: "comment_id")
        try values.encode(isDeleted, forKey: "deleted")
        try values.encode(auth, forKey: "auth")
    }
}
