// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct DeleteAccount: Codable {
    /// DeleteAccount.password
    public var password: String
    /// DeleteAccount.auth
    public var auth: String

    public init(password: String, auth: String) {
        self.password = password
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.password = try values.decode(String.self, forKey: "password")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(password, forKey: "password")
        try values.encode(auth, forKey: "auth")
    }
}
