// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct DeleteCustomEmoji: Codable {
    /// CustomEmojiId
    public var id: Double
    /// DeleteCustomEmoji.auth
    public var auth: String

    public init(id: Double, auth: String) {
        self.id = id
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Double.self, forKey: "id")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(auth, forKey: "auth")
    }
}
