// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct DeletePrivateMessage: Codable {
    public var privateMessageID: Double
    /// DeletePrivateMessage.deleted
    public var isDeleted: Bool
    /// DeletePrivateMessage.auth
    public var auth: String

    public init(privateMessageID: Double, isDeleted: Bool, auth: String) {
        self.privateMessageID = privateMessageID
        self.isDeleted = isDeleted
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.privateMessageID = try values.decode(Double.self, forKey: "private_message_id")
        self.isDeleted = try values.decode(Bool.self, forKey: "deleted")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(privateMessageID, forKey: "private_message_id")
        try values.encode(isDeleted, forKey: "deleted")
        try values.encode(auth, forKey: "auth")
    }
}
