// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct DeleteCustomEmojiResponse: Codable {
    /// CustomEmojiId
    public var id: Double
    /// DeleteCustomEmojiResponse.success
    public var isSuccess: Bool

    public init(id: Double, isSuccess: Bool) {
        self.id = id
        self.isSuccess = isSuccess
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Double.self, forKey: "id")
        self.isSuccess = try values.decode(Bool.self, forKey: "success")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(isSuccess, forKey: "success")
    }
}
