// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct EditPrivateMessage: Codable {
    public var privateMessageID: Double
    /// EditPrivateMessage.content
    public var content: String
    /// EditPrivateMessage.auth
    public var auth: String

    public init(privateMessageID: Double, content: String, auth: String) {
        self.privateMessageID = privateMessageID
        self.content = content
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.privateMessageID = try values.decode(Double.self, forKey: "private_message_id")
        self.content = try values.decode(String.self, forKey: "content")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(privateMessageID, forKey: "private_message_id")
        try values.encode(content, forKey: "content")
        try values.encode(auth, forKey: "auth")
    }
}
