// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct EditCustomEmoji: Codable {
    /// CustomEmojiId
    public var id: Double
    /// EditCustomEmoji.category
    public var category: String
    /// EditCustomEmoji.image_url
    public var imageURL: String
    /// EditCustomEmoji.alt_text
    public var altText: String
    /// EditCustomEmoji.keywords
    public var keywords: [String]
    /// EditCustomEmoji.auth
    public var auth: String

    public init(id: Double, category: String, imageURL: String, altText: String, keywords: [String], auth: String) {
        self.id = id
        self.category = category
        self.imageURL = imageURL
        self.altText = altText
        self.keywords = keywords
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Double.self, forKey: "id")
        self.category = try values.decode(String.self, forKey: "category")
        self.imageURL = try values.decode(String.self, forKey: "image_url")
        self.altText = try values.decode(String.self, forKey: "alt_text")
        self.keywords = try values.decode([String].self, forKey: "keywords")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(category, forKey: "category")
        try values.encode(imageURL, forKey: "image_url")
        try values.encode(altText, forKey: "alt_text")
        try values.encode(keywords, forKey: "keywords")
        try values.encode(auth, forKey: "auth")
    }
}
