// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct EditComment: Codable {
    public var commentID: Double
    /// EditComment.content
    public var content: String?
    public var languageID: Double?
    /// EditComment.form_id
    public var formID: String?
    /// EditComment.auth
    public var auth: String

    public init(commentID: Double, content: String? = nil, languageID: Double? = nil, formID: String? = nil, auth: String) {
        self.commentID = commentID
        self.content = content
        self.languageID = languageID
        self.formID = formID
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.commentID = try values.decode(Double.self, forKey: "comment_id")
        self.content = try values.decodeIfPresent(String.self, forKey: "content")
        self.languageID = try values.decodeIfPresent(Double.self, forKey: "language_id")
        self.formID = try values.decodeIfPresent(String.self, forKey: "form_id")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(commentID, forKey: "comment_id")
        try values.encodeIfPresent(content, forKey: "content")
        try values.encodeIfPresent(languageID, forKey: "language_id")
        try values.encodeIfPresent(formID, forKey: "form_id")
        try values.encode(auth, forKey: "auth")
    }
}
