// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ErrorResponseLogin: Codable {
    public var error: Error?

    public enum Error: String, Codable, CaseIterable {
        case incorrectLogin = "incorrect_login"
        case emailNotVerified = "email_not_verified"
        case registrationDenied = "registration_denied"
        case registrationApplicationPending = "registration_application_pending"
        case registrationApplicationIsPending = "registration_application_is_pending"
        case missingTotpToken = "missing_totp_token"
        case incorrectTotpToke = "incorrect_totp_toke"
    }

    public init(error: Error? = nil) {
        self.error = error
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.error = try values.decodeIfPresent(Error.self, forKey: "error")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(error, forKey: "error")
    }
}
