// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ErrorResponseRegistration: Codable {
    public var error: Error?

    public enum Error: String, Codable, CaseIterable {
        case registrationClosed = "registration_closed"
        case emailRequired = "email_required"
        case registrationApplicationAnswerRequired = "registration_application_answer_required"
        case passwordsDoNotMatch = "passwords_do_not_match"
        case captchaIncorrect = "captcha_incorrect"
        case emailAlreadyExists = "email_already_exists"
        case userAlreadyExists = "user_already_exists"
    }

    public init(error: Error? = nil) {
        self.error = error
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.error = try values.decodeIfPresent(Error.self, forKey: "error")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(error, forKey: "error")
    }
}
