// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct FeaturePost: Codable {
    public var postID: Double
    /// FeaturePost.featured
    public var isFeatured: Bool
    /// PostFeatureType
    public var featureType: PostFeatureType
    /// FeaturePost.auth
    public var auth: String

    public init(postID: Double, isFeatured: Bool, featureType: PostFeatureType, auth: String) {
        self.postID = postID
        self.isFeatured = isFeatured
        self.featureType = featureType
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.postID = try values.decode(Double.self, forKey: "post_id")
        self.isFeatured = try values.decode(Bool.self, forKey: "featured")
        self.featureType = try values.decode(PostFeatureType.self, forKey: "feature_type")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(postID, forKey: "post_id")
        try values.encode(isFeatured, forKey: "featured")
        try values.encode(featureType, forKey: "feature_type")
        try values.encode(auth, forKey: "auth")
    }
}
