// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct FederatedInstances: Codable {
    /// FederatedInstances.linked
    public var linked: [Instance]
    /// FederatedInstances.allowed
    public var allowed: [Instance]
    /// FederatedInstances.blocked
    public var blocked: [Instance]

    public init(linked: [Instance], allowed: [Instance], blocked: [Instance]) {
        self.linked = linked
        self.allowed = allowed
        self.blocked = blocked
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.linked = try values.decode([Instance].self, forKey: "linked")
        self.allowed = try values.decode([Instance].self, forKey: "allowed")
        self.blocked = try values.decode([Instance].self, forKey: "blocked")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(linked, forKey: "linked")
        try values.encode(allowed, forKey: "allowed")
        try values.encode(blocked, forKey: "blocked")
    }
}
