// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetComment: Codable {
    /// CommentId
    public var id: Double
    /// GetComment.auth
    public var auth: String?

    public init(id: Double, auth: String? = nil) {
        self.id = id
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Double.self, forKey: "id")
        self.auth = try values.decodeIfPresent(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encodeIfPresent(auth, forKey: "auth")
    }
}
