// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetCaptchaResponse: Codable {
    /// CaptchaResponse
    public var ok: CaptchaResponse?

    public init(ok: CaptchaResponse? = nil) {
        self.ok = ok
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.ok = try values.decodeIfPresent(CaptchaResponse.self, forKey: "ok")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(ok, forKey: "ok")
    }
}
