// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetCommentsResponse: Codable {
    /// GetCommentsResponse.comments
    public var comments: [CommentView]

    public init(comments: [CommentView]) {
        self.comments = comments
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.comments = try values.decode([CommentView].self, forKey: "comments")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(comments, forKey: "comments")
    }
}
