// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetCommunity: Codable {
    /// CommunityId
    public var id: Double?
    /// GetCommunity.name
    public var name: String?
    /// GetCommunity.auth
    public var auth: String?

    public init(id: Double? = nil, name: String? = nil, auth: String? = nil) {
        self.id = id
        self.name = name
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(Double.self, forKey: "id")
        self.name = try values.decodeIfPresent(String.self, forKey: "name")
        self.auth = try values.decodeIfPresent(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(name, forKey: "name")
        try values.encodeIfPresent(auth, forKey: "auth")
    }
}
