// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetComments: Codable {
    /// ListingType
    public var type: ListingType?
    /// CommentSortType
    public var sort: CommentSortType?
    /// GetComments.max_depth
    public var maxDepth: Double?
    /// GetComments.page
    public var page: Double?
    /// GetComments.limit
    public var limit: Double?
    public var communityID: Double?
    /// GetComments.community_name
    public var communityName: String?
    public var postID: Double?
    /// CommentId
    public var parentID: Double?
    /// GetComments.saved_only
    public var isSavedOnly: Bool?
    /// GetComments.auth
    public var auth: String?

    public init(type: ListingType? = nil, sort: CommentSortType? = nil, maxDepth: Double? = nil, page: Double? = nil, limit: Double? = nil, communityID: Double? = nil, communityName: String? = nil, postID: Double? = nil, parentID: Double? = nil, isSavedOnly: Bool? = nil, auth: String? = nil) {
        self.type = type
        self.sort = sort
        self.maxDepth = maxDepth
        self.page = page
        self.limit = limit
        self.communityID = communityID
        self.communityName = communityName
        self.postID = postID
        self.parentID = parentID
        self.isSavedOnly = isSavedOnly
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.type = try values.decodeIfPresent(ListingType.self, forKey: "type_")
        self.sort = try values.decodeIfPresent(CommentSortType.self, forKey: "sort")
        self.maxDepth = try values.decodeIfPresent(Double.self, forKey: "max_depth")
        self.page = try values.decodeIfPresent(Double.self, forKey: "page")
        self.limit = try values.decodeIfPresent(Double.self, forKey: "limit")
        self.communityID = try values.decodeIfPresent(Double.self, forKey: "community_id")
        self.communityName = try values.decodeIfPresent(String.self, forKey: "community_name")
        self.postID = try values.decodeIfPresent(Double.self, forKey: "post_id")
        self.parentID = try values.decodeIfPresent(Double.self, forKey: "parent_id")
        self.isSavedOnly = try values.decodeIfPresent(Bool.self, forKey: "saved_only")
        self.auth = try values.decodeIfPresent(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(type, forKey: "type_")
        try values.encodeIfPresent(sort, forKey: "sort")
        try values.encodeIfPresent(maxDepth, forKey: "max_depth")
        try values.encodeIfPresent(page, forKey: "page")
        try values.encodeIfPresent(limit, forKey: "limit")
        try values.encodeIfPresent(communityID, forKey: "community_id")
        try values.encodeIfPresent(communityName, forKey: "community_name")
        try values.encodeIfPresent(postID, forKey: "post_id")
        try values.encodeIfPresent(parentID, forKey: "parent_id")
        try values.encodeIfPresent(isSavedOnly, forKey: "saved_only")
        try values.encodeIfPresent(auth, forKey: "auth")
    }
}
