// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetPostResponse: Codable {
    public var postView: PostView
    public var communityView: CommunityView
    /// GetPostResponse.moderators
    public var moderators: [CommunityModeratorView]
    /// GetPostResponse.cross_posts
    public var crossPosts: [PostView]

    public init(postView: PostView, communityView: CommunityView, moderators: [CommunityModeratorView], crossPosts: [PostView]) {
        self.postView = postView
        self.communityView = communityView
        self.moderators = moderators
        self.crossPosts = crossPosts
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.postView = try values.decode(PostView.self, forKey: "post_view")
        self.communityView = try values.decode(CommunityView.self, forKey: "community_view")
        self.moderators = try values.decode([CommunityModeratorView].self, forKey: "moderators")
        self.crossPosts = try values.decode([PostView].self, forKey: "cross_posts")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(postView, forKey: "post_view")
        try values.encode(communityView, forKey: "community_view")
        try values.encode(moderators, forKey: "moderators")
        try values.encode(crossPosts, forKey: "cross_posts")
    }
}
