// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetPost: Codable {
    /// PostId
    public var id: Double?
    public var commentID: Double?
    /// GetPost.auth
    public var auth: String?

    public init(id: Double? = nil, commentID: Double? = nil, auth: String? = nil) {
        self.id = id
        self.commentID = commentID
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(Double.self, forKey: "id")
        self.commentID = try values.decodeIfPresent(Double.self, forKey: "comment_id")
        self.auth = try values.decodeIfPresent(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(commentID, forKey: "comment_id")
        try values.encodeIfPresent(auth, forKey: "auth")
    }
}
