// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetPersonDetailsResponse: Codable {
    public var personView: PersonView
    /// GetPersonDetailsResponse.comments
    public var comments: [CommentView]
    /// GetPersonDetailsResponse.posts
    public var posts: [PostView]
    /// GetPersonDetailsResponse.moderates
    public var moderates: [CommunityModeratorView]

    public init(personView: PersonView, comments: [CommentView], posts: [PostView], moderates: [CommunityModeratorView]) {
        self.personView = personView
        self.comments = comments
        self.posts = posts
        self.moderates = moderates
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.personView = try values.decode(PersonView.self, forKey: "person_view")
        self.comments = try values.decode([CommentView].self, forKey: "comments")
        self.posts = try values.decode([PostView].self, forKey: "posts")
        self.moderates = try values.decode([CommunityModeratorView].self, forKey: "moderates")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(personView, forKey: "person_view")
        try values.encode(comments, forKey: "comments")
        try values.encode(posts, forKey: "posts")
        try values.encode(moderates, forKey: "moderates")
    }
}
