// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetPersonMentions: Codable {
    /// CommentSortType
    public var sort: CommentSortType?
    /// GetPersonMentions.page
    public var page: Double?
    /// GetPersonMentions.limit
    public var limit: Double?
    /// GetPersonMentions.unread_only
    public var isUnreadOnly: Bool?
    /// GetPersonMentions.auth
    public var auth: String

    public init(sort: CommentSortType? = nil, page: Double? = nil, limit: Double? = nil, isUnreadOnly: Bool? = nil, auth: String) {
        self.sort = sort
        self.page = page
        self.limit = limit
        self.isUnreadOnly = isUnreadOnly
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.sort = try values.decodeIfPresent(CommentSortType.self, forKey: "sort")
        self.page = try values.decodeIfPresent(Double.self, forKey: "page")
        self.limit = try values.decodeIfPresent(Double.self, forKey: "limit")
        self.isUnreadOnly = try values.decodeIfPresent(Bool.self, forKey: "unread_only")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(sort, forKey: "sort")
        try values.encodeIfPresent(page, forKey: "page")
        try values.encodeIfPresent(limit, forKey: "limit")
        try values.encodeIfPresent(isUnreadOnly, forKey: "unread_only")
        try values.encode(auth, forKey: "auth")
    }
}
