// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetPersonMentionsResponse: Codable {
    /// GetPersonMentionsResponse.mentions
    public var mentions: [PersonMentionView]

    public init(mentions: [PersonMentionView]) {
        self.mentions = mentions
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.mentions = try values.decode([PersonMentionView].self, forKey: "mentions")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(mentions, forKey: "mentions")
    }
}
