// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetReportCountResponse: Codable {
    public var communityID: Double?
    /// GetReportCountResponse.comment_reports
    public var commentReports: Double
    /// GetReportCountResponse.post_reports
    public var postReports: Double
    /// GetReportCountResponse.private_message_reports
    public var privateMessageReports: Double?

    public init(communityID: Double? = nil, commentReports: Double, postReports: Double, privateMessageReports: Double? = nil) {
        self.communityID = communityID
        self.commentReports = commentReports
        self.postReports = postReports
        self.privateMessageReports = privateMessageReports
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.communityID = try values.decodeIfPresent(Double.self, forKey: "community_id")
        self.commentReports = try values.decode(Double.self, forKey: "comment_reports")
        self.postReports = try values.decode(Double.self, forKey: "post_reports")
        self.privateMessageReports = try values.decodeIfPresent(Double.self, forKey: "private_message_reports")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(communityID, forKey: "community_id")
        try values.encode(commentReports, forKey: "comment_reports")
        try values.encode(postReports, forKey: "post_reports")
        try values.encodeIfPresent(privateMessageReports, forKey: "private_message_reports")
    }
}
