// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetRepliesResponse: Codable {
    /// GetRepliesResponse.replies
    public var replies: [CommentReplyView]

    public init(replies: [CommentReplyView]) {
        self.replies = replies
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.replies = try values.decode([CommentReplyView].self, forKey: "replies")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(replies, forKey: "replies")
    }
}
