// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetReportCount: Codable {
    public var communityID: Double?
    /// GetReportCount.auth
    public var auth: String

    public init(communityID: Double? = nil, auth: String) {
        self.communityID = communityID
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.communityID = try values.decodeIfPresent(Double.self, forKey: "community_id")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(communityID, forKey: "community_id")
        try values.encode(auth, forKey: "auth")
    }
}
