// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetSite: Codable {
    /// GetSite.auth
    public var auth: String?

    public init(auth: String? = nil) {
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.auth = try values.decodeIfPresent(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(auth, forKey: "auth")
    }
}
