// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetSiteMetadataResponse: Codable {
    /// SiteMetadata
    public var metadata: SiteMetadata

    public init(metadata: SiteMetadata) {
        self.metadata = metadata
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.metadata = try values.decode(SiteMetadata.self, forKey: "metadata")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(metadata, forKey: "metadata")
    }
}
