// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetSiteResponse: Codable {
    public var siteView: SiteView
    /// GetSiteResponse.admins
    public var admins: [PersonView]
    /// GetSiteResponse.version
    public var version: String
    /// MyUserInfo
    public var myUser: MyUserInfo?
    /// GetSiteResponse.all_languages
    public var allLanguages: [Language]
    /// GetSiteResponse.discussion_languages
    public var discussionLanguages: [Double]
    /// GetSiteResponse.taglines
    public var taglines: [Tagline]
    /// GetSiteResponse.custom_emojis
    public var customEmojis: [CustomEmojiView]

    public init(siteView: SiteView, admins: [PersonView], version: String, myUser: MyUserInfo? = nil, allLanguages: [Language], discussionLanguages: [Double], taglines: [Tagline], customEmojis: [CustomEmojiView]) {
        self.siteView = siteView
        self.admins = admins
        self.version = version
        self.myUser = myUser
        self.allLanguages = allLanguages
        self.discussionLanguages = discussionLanguages
        self.taglines = taglines
        self.customEmojis = customEmojis
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.siteView = try values.decode(SiteView.self, forKey: "site_view")
        self.admins = try values.decode([PersonView].self, forKey: "admins")
        self.version = try values.decode(String.self, forKey: "version")
        self.myUser = try values.decodeIfPresent(MyUserInfo.self, forKey: "my_user")
        self.allLanguages = try values.decode([Language].self, forKey: "all_languages")
        self.discussionLanguages = try values.decode([Double].self, forKey: "discussion_languages")
        self.taglines = try values.decode([Tagline].self, forKey: "taglines")
        self.customEmojis = try values.decode([CustomEmojiView].self, forKey: "custom_emojis")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(siteView, forKey: "site_view")
        try values.encode(admins, forKey: "admins")
        try values.encode(version, forKey: "version")
        try values.encodeIfPresent(myUser, forKey: "my_user")
        try values.encode(allLanguages, forKey: "all_languages")
        try values.encode(discussionLanguages, forKey: "discussion_languages")
        try values.encode(taglines, forKey: "taglines")
        try values.encode(customEmojis, forKey: "custom_emojis")
    }
}
