// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetUnreadRegistrationApplicationCountResponse: Codable {
    /// GetUnreadRegistrationApplicationCountResponse.registration_applications
    public var registrationApplications: Double

    public init(registrationApplications: Double) {
        self.registrationApplications = registrationApplications
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.registrationApplications = try values.decode(Double.self, forKey: "registration_applications")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(registrationApplications, forKey: "registration_applications")
    }
}
