// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GetUnreadCountResponse: Codable {
    /// GetUnreadCountResponse.replies
    public var replies: Double
    /// GetUnreadCountResponse.mentions
    public var mentions: Double
    /// GetUnreadCountResponse.private_messages
    public var privateMessages: Double

    public init(replies: Double, mentions: Double, privateMessages: Double) {
        self.replies = replies
        self.mentions = mentions
        self.privateMessages = privateMessages
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.replies = try values.decode(Double.self, forKey: "replies")
        self.mentions = try values.decode(Double.self, forKey: "mentions")
        self.privateMessages = try values.decode(Double.self, forKey: "private_messages")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(replies, forKey: "replies")
        try values.encode(mentions, forKey: "mentions")
        try values.encode(privateMessages, forKey: "private_messages")
    }
}
