// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Language: Codable {
    /// LanguageId
    public var id: Double
    /// Language.code
    public var code: String
    /// Language.name
    public var name: String

    public init(id: Double, code: String, name: String) {
        self.id = id
        self.code = code
        self.name = name
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Double.self, forKey: "id")
        self.code = try values.decode(String.self, forKey: "code")
        self.name = try values.decode(String.self, forKey: "name")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(code, forKey: "code")
        try values.encode(name, forKey: "name")
    }
}
