// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct LeaveAdmin: Codable {
    /// LeaveAdmin.auth
    public var auth: String

    public init(auth: String) {
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(auth, forKey: "auth")
    }
}
