// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ListCommentReportsResponse: Codable {
    /// ListCommentReportsResponse.comment_reports
    public var commentReports: [CommentReportView]

    public init(commentReports: [CommentReportView]) {
        self.commentReports = commentReports
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.commentReports = try values.decode([CommentReportView].self, forKey: "comment_reports")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(commentReports, forKey: "comment_reports")
    }
}
