// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ListCommunities: Codable {
    /// ListingType
    public var type: ListingType?
    /// SortType
    public var sort: SortType?
    /// ListCommunities.show_nsfw
    public var isShowNsfw: Bool?
    /// ListCommunities.page
    public var page: Double?
    /// ListCommunities.limit
    public var limit: Double?
    /// ListCommunities.auth
    public var auth: String?

    public init(type: ListingType? = nil, sort: SortType? = nil, isShowNsfw: Bool? = nil, page: Double? = nil, limit: Double? = nil, auth: String? = nil) {
        self.type = type
        self.sort = sort
        self.isShowNsfw = isShowNsfw
        self.page = page
        self.limit = limit
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.type = try values.decodeIfPresent(ListingType.self, forKey: "type_")
        self.sort = try values.decodeIfPresent(SortType.self, forKey: "sort")
        self.isShowNsfw = try values.decodeIfPresent(Bool.self, forKey: "show_nsfw")
        self.page = try values.decodeIfPresent(Double.self, forKey: "page")
        self.limit = try values.decodeIfPresent(Double.self, forKey: "limit")
        self.auth = try values.decodeIfPresent(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(type, forKey: "type_")
        try values.encodeIfPresent(sort, forKey: "sort")
        try values.encodeIfPresent(isShowNsfw, forKey: "show_nsfw")
        try values.encodeIfPresent(page, forKey: "page")
        try values.encodeIfPresent(limit, forKey: "limit")
        try values.encodeIfPresent(auth, forKey: "auth")
    }
}
