// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public enum ListingType: String, Codable, CaseIterable {
    case all = "All"
    case local = "Local"
    case subscribed = "Subscribed"
}
