// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ListRegistrationApplicationsResponse: Codable {
    /// ListRegistrationApplicationsResponse.registration_applications
    public var registrationApplications: [RegistrationApplicationView]

    public init(registrationApplications: [RegistrationApplicationView]) {
        self.registrationApplications = registrationApplications
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.registrationApplications = try values.decode([RegistrationApplicationView].self, forKey: "registration_applications")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(registrationApplications, forKey: "registration_applications")
    }
}
