// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ListPostReportsResponse: Codable {
    /// ListPostReportsResponse.post_reports
    public var postReports: [PostReportView]

    public init(postReports: [PostReportView]) {
        self.postReports = postReports
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.postReports = try values.decode([PostReportView].self, forKey: "post_reports")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(postReports, forKey: "post_reports")
    }
}
