// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ListPrivateMessageReportsResponse: Codable {
    /// ListPrivateMessageReportsResponse.private_message_reports
    public var privateMessageReports: [PrivateMessageReportView]

    public init(privateMessageReports: [PrivateMessageReportView]) {
        self.privateMessageReports = privateMessageReports
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.privateMessageReports = try values.decode([PrivateMessageReportView].self, forKey: "private_message_reports")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(privateMessageReports, forKey: "private_message_reports")
    }
}
