// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct LocalUserView: Codable {
    public var localUser: LocalUser
    public var person: Person
    /// PersonAggregates
    public var counts: PersonAggregates

    public init(localUser: LocalUser, person: Person, counts: PersonAggregates) {
        self.localUser = localUser
        self.person = person
        self.counts = counts
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.localUser = try values.decode(LocalUser.self, forKey: "local_user")
        self.person = try values.decode(Person.self, forKey: "person")
        self.counts = try values.decode(PersonAggregates.self, forKey: "counts")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(localUser, forKey: "local_user")
        try values.encode(person, forKey: "person")
        try values.encode(counts, forKey: "counts")
    }
}
