// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct LockPost: Codable {
    public var postID: Double
    /// LockPost.locked
    public var isLocked: Bool
    /// LockPost.auth
    public var auth: String

    public init(postID: Double, isLocked: Bool, auth: String) {
        self.postID = postID
        self.isLocked = isLocked
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.postID = try values.decode(Double.self, forKey: "post_id")
        self.isLocked = try values.decode(Bool.self, forKey: "locked")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(postID, forKey: "post_id")
        try values.encode(isLocked, forKey: "locked")
        try values.encode(auth, forKey: "auth")
    }
}
