// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Login: Codable {
    /// Login.username_or_email
    public var usernameOrEmail: String
    /// Login.password
    public var password: String
    /// Login.totp_2fa_token
    public var totp2faToken: String?

    public init(usernameOrEmail: String, password: String, totp2faToken: String? = nil) {
        self.usernameOrEmail = usernameOrEmail
        self.password = password
        self.totp2faToken = totp2faToken
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.usernameOrEmail = try values.decode(String.self, forKey: "username_or_email")
        self.password = try values.decode(String.self, forKey: "password")
        self.totp2faToken = try values.decodeIfPresent(String.self, forKey: "totp_2fa_token")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(usernameOrEmail, forKey: "username_or_email")
        try values.encode(password, forKey: "password")
        try values.encodeIfPresent(totp2faToken, forKey: "totp_2fa_token")
    }
}
