// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct LoginResponse: Codable {
    /// LoginResponse.jwt
    public var jwt: String?
    /// LoginResponse.registration_created
    public var isRegistrationCreated: Bool
    /// LoginResponse.verify_email_sent
    public var isVerifyEmailSent: Bool

    public init(jwt: String? = nil, isRegistrationCreated: Bool, isVerifyEmailSent: Bool) {
        self.jwt = jwt
        self.isRegistrationCreated = isRegistrationCreated
        self.isVerifyEmailSent = isVerifyEmailSent
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.jwt = try values.decodeIfPresent(String.self, forKey: "jwt")
        self.isRegistrationCreated = try values.decode(Bool.self, forKey: "registration_created")
        self.isVerifyEmailSent = try values.decode(Bool.self, forKey: "verify_email_sent")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(jwt, forKey: "jwt")
        try values.encode(isRegistrationCreated, forKey: "registration_created")
        try values.encode(isVerifyEmailSent, forKey: "verify_email_sent")
    }
}
