// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct MarkPostAsRead: Codable {
    public var postID: Double
    /// MarkPostAsRead.read
    public var isRead: Bool
    /// MarkPostAsRead.auth
    public var auth: String

    public init(postID: Double, isRead: Bool, auth: String) {
        self.postID = postID
        self.isRead = isRead
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.postID = try values.decode(Double.self, forKey: "post_id")
        self.isRead = try values.decode(Bool.self, forKey: "read")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(postID, forKey: "post_id")
        try values.encode(isRead, forKey: "read")
        try values.encode(auth, forKey: "auth")
    }
}
