// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct MarkPersonMentionAsRead: Codable {
    public var personMentionID: Double
    /// MarkPersonMentionAsRead.read
    public var isRead: Bool
    /// MarkPersonMentionAsRead.auth
    public var auth: String

    public init(personMentionID: Double, isRead: Bool, auth: String) {
        self.personMentionID = personMentionID
        self.isRead = isRead
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.personMentionID = try values.decode(Double.self, forKey: "person_mention_id")
        self.isRead = try values.decode(Bool.self, forKey: "read")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(personMentionID, forKey: "person_mention_id")
        try values.encode(isRead, forKey: "read")
        try values.encode(auth, forKey: "auth")
    }
}
