// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct MarkCommentReplyAsRead: Codable {
    public var commentReplyID: Double
    /// MarkCommentReplyAsRead.read
    public var isRead: Bool
    /// MarkCommentReplyAsRead.auth
    public var auth: String

    public init(commentReplyID: Double, isRead: Bool, auth: String) {
        self.commentReplyID = commentReplyID
        self.isRead = isRead
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.commentReplyID = try values.decode(Double.self, forKey: "comment_reply_id")
        self.isRead = try values.decode(Bool.self, forKey: "read")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(commentReplyID, forKey: "comment_reply_id")
        try values.encode(isRead, forKey: "read")
        try values.encode(auth, forKey: "auth")
    }
}
