// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ModAddView: Codable {
    public var modAdd: ModAdd
    /// Person
    public var moderator: Person?
    /// Person
    public var moddedPerson: Person

    public init(modAdd: ModAdd, moderator: Person? = nil, moddedPerson: Person) {
        self.modAdd = modAdd
        self.moderator = moderator
        self.moddedPerson = moddedPerson
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.modAdd = try values.decode(ModAdd.self, forKey: "mod_add")
        self.moderator = try values.decodeIfPresent(Person.self, forKey: "moderator")
        self.moddedPerson = try values.decode(Person.self, forKey: "modded_person")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(modAdd, forKey: "mod_add")
        try values.encodeIfPresent(moderator, forKey: "moderator")
        try values.encode(moddedPerson, forKey: "modded_person")
    }
}
