// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ModAdd: Codable {
    /// ModAdd.id
    public var id: Double
    /// PersonId
    public var modPersonID: Double
    /// PersonId
    public var otherPersonID: Double
    /// ModAdd.removed
    public var isRemoved: Bool
    /// ModAdd.when_
    public var when: String

    public init(id: Double, modPersonID: Double, otherPersonID: Double, isRemoved: Bool, when: String) {
        self.id = id
        self.modPersonID = modPersonID
        self.otherPersonID = otherPersonID
        self.isRemoved = isRemoved
        self.when = when
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Double.self, forKey: "id")
        self.modPersonID = try values.decode(Double.self, forKey: "mod_person_id")
        self.otherPersonID = try values.decode(Double.self, forKey: "other_person_id")
        self.isRemoved = try values.decode(Bool.self, forKey: "removed")
        self.when = try values.decode(String.self, forKey: "when_")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(modPersonID, forKey: "mod_person_id")
        try values.encode(otherPersonID, forKey: "other_person_id")
        try values.encode(isRemoved, forKey: "removed")
        try values.encode(when, forKey: "when_")
    }
}
