// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ModAddCommunityView: Codable {
    public var modAddCommunity: ModAddCommunity
    /// Person
    public var moderator: Person?
    public var community: Community
    /// Person
    public var moddedPerson: Person

    public init(modAddCommunity: ModAddCommunity, moderator: Person? = nil, community: Community, moddedPerson: Person) {
        self.modAddCommunity = modAddCommunity
        self.moderator = moderator
        self.community = community
        self.moddedPerson = moddedPerson
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.modAddCommunity = try values.decode(ModAddCommunity.self, forKey: "mod_add_community")
        self.moderator = try values.decodeIfPresent(Person.self, forKey: "moderator")
        self.community = try values.decode(Community.self, forKey: "community")
        self.moddedPerson = try values.decode(Person.self, forKey: "modded_person")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(modAddCommunity, forKey: "mod_add_community")
        try values.encodeIfPresent(moderator, forKey: "moderator")
        try values.encode(community, forKey: "community")
        try values.encode(moddedPerson, forKey: "modded_person")
    }
}
