// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ModBan: Codable {
    /// ModBan.id
    public var id: Double
    /// PersonId
    public var modPersonID: Double
    /// PersonId
    public var otherPersonID: Double
    /// ModBan.reason
    public var reason: String?
    /// ModBan.banned
    public var isBanned: Bool
    /// ModBan.expires
    public var expires: String?
    /// ModBan.when_
    public var when: String

    public init(id: Double, modPersonID: Double, otherPersonID: Double, reason: String? = nil, isBanned: Bool, expires: String? = nil, when: String) {
        self.id = id
        self.modPersonID = modPersonID
        self.otherPersonID = otherPersonID
        self.reason = reason
        self.isBanned = isBanned
        self.expires = expires
        self.when = when
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Double.self, forKey: "id")
        self.modPersonID = try values.decode(Double.self, forKey: "mod_person_id")
        self.otherPersonID = try values.decode(Double.self, forKey: "other_person_id")
        self.reason = try values.decodeIfPresent(String.self, forKey: "reason")
        self.isBanned = try values.decode(Bool.self, forKey: "banned")
        self.expires = try values.decodeIfPresent(String.self, forKey: "expires")
        self.when = try values.decode(String.self, forKey: "when_")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(modPersonID, forKey: "mod_person_id")
        try values.encode(otherPersonID, forKey: "other_person_id")
        try values.encodeIfPresent(reason, forKey: "reason")
        try values.encode(isBanned, forKey: "banned")
        try values.encodeIfPresent(expires, forKey: "expires")
        try values.encode(when, forKey: "when_")
    }
}
