// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ModBanFromCommunityView: Codable {
    public var modBanFromCommunity: ModBanFromCommunity
    /// Person
    public var moderator: Person?
    public var community: Community
    /// Person
    public var bannedPerson: Person

    public init(modBanFromCommunity: ModBanFromCommunity, moderator: Person? = nil, community: Community, bannedPerson: Person) {
        self.modBanFromCommunity = modBanFromCommunity
        self.moderator = moderator
        self.community = community
        self.bannedPerson = bannedPerson
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.modBanFromCommunity = try values.decode(ModBanFromCommunity.self, forKey: "mod_ban_from_community")
        self.moderator = try values.decodeIfPresent(Person.self, forKey: "moderator")
        self.community = try values.decode(Community.self, forKey: "community")
        self.bannedPerson = try values.decode(Person.self, forKey: "banned_person")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(modBanFromCommunity, forKey: "mod_ban_from_community")
        try values.encodeIfPresent(moderator, forKey: "moderator")
        try values.encode(community, forKey: "community")
        try values.encode(bannedPerson, forKey: "banned_person")
    }
}
