// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ModFeaturePostView: Codable {
    public var modFeaturePost: ModFeaturePost
    /// Person
    public var moderator: Person?
    public var post: Post
    public var community: Community

    public init(modFeaturePost: ModFeaturePost, moderator: Person? = nil, post: Post, community: Community) {
        self.modFeaturePost = modFeaturePost
        self.moderator = moderator
        self.post = post
        self.community = community
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.modFeaturePost = try values.decode(ModFeaturePost.self, forKey: "mod_feature_post")
        self.moderator = try values.decodeIfPresent(Person.self, forKey: "moderator")
        self.post = try values.decode(Post.self, forKey: "post")
        self.community = try values.decode(Community.self, forKey: "community")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(modFeaturePost, forKey: "mod_feature_post")
        try values.encodeIfPresent(moderator, forKey: "moderator")
        try values.encode(post, forKey: "post")
        try values.encode(community, forKey: "community")
    }
}
