// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ModFeaturePost: Codable {
    /// ModFeaturePost.id
    public var id: Double
    /// PersonId
    public var modPersonID: Double
    public var postID: Double
    /// ModFeaturePost.featured
    public var isFeatured: Bool
    /// ModFeaturePost.when_
    public var when: String
    /// ModFeaturePost.is_featured_community
    public var isFeaturedCommunity: Bool

    public init(id: Double, modPersonID: Double, postID: Double, isFeatured: Bool, when: String, isFeaturedCommunity: Bool) {
        self.id = id
        self.modPersonID = modPersonID
        self.postID = postID
        self.isFeatured = isFeatured
        self.when = when
        self.isFeaturedCommunity = isFeaturedCommunity
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Double.self, forKey: "id")
        self.modPersonID = try values.decode(Double.self, forKey: "mod_person_id")
        self.postID = try values.decode(Double.self, forKey: "post_id")
        self.isFeatured = try values.decode(Bool.self, forKey: "featured")
        self.when = try values.decode(String.self, forKey: "when_")
        self.isFeaturedCommunity = try values.decode(Bool.self, forKey: "is_featured_community")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(modPersonID, forKey: "mod_person_id")
        try values.encode(postID, forKey: "post_id")
        try values.encode(isFeatured, forKey: "featured")
        try values.encode(when, forKey: "when_")
        try values.encode(isFeaturedCommunity, forKey: "is_featured_community")
    }
}
