// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ModHideCommunityView: Codable {
    public var modHideCommunity: ModHideCommunity
    /// Person
    public var admin: Person?
    public var community: Community

    public init(modHideCommunity: ModHideCommunity, admin: Person? = nil, community: Community) {
        self.modHideCommunity = modHideCommunity
        self.admin = admin
        self.community = community
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.modHideCommunity = try values.decode(ModHideCommunity.self, forKey: "mod_hide_community")
        self.admin = try values.decodeIfPresent(Person.self, forKey: "admin")
        self.community = try values.decode(Community.self, forKey: "community")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(modHideCommunity, forKey: "mod_hide_community")
        try values.encodeIfPresent(admin, forKey: "admin")
        try values.encode(community, forKey: "community")
    }
}
