// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ModHideCommunity: Codable {
    /// ModHideCommunity.id
    public var id: Double
    public var communityID: Double
    /// PersonId
    public var modPersonID: Double
    /// ModHideCommunity.when_
    public var when: String
    /// ModHideCommunity.reason
    public var reason: String?
    /// ModHideCommunity.hidden
    public var isHidden: Bool

    public init(id: Double, communityID: Double, modPersonID: Double, when: String, reason: String? = nil, isHidden: Bool) {
        self.id = id
        self.communityID = communityID
        self.modPersonID = modPersonID
        self.when = when
        self.reason = reason
        self.isHidden = isHidden
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Double.self, forKey: "id")
        self.communityID = try values.decode(Double.self, forKey: "community_id")
        self.modPersonID = try values.decode(Double.self, forKey: "mod_person_id")
        self.when = try values.decode(String.self, forKey: "when_")
        self.reason = try values.decodeIfPresent(String.self, forKey: "reason")
        self.isHidden = try values.decode(Bool.self, forKey: "hidden")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(communityID, forKey: "community_id")
        try values.encode(modPersonID, forKey: "mod_person_id")
        try values.encode(when, forKey: "when_")
        try values.encodeIfPresent(reason, forKey: "reason")
        try values.encode(isHidden, forKey: "hidden")
    }
}
