// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ModLockPost: Codable {
    /// ModLockPost.id
    public var id: Double
    /// PersonId
    public var modPersonID: Double
    public var postID: Double
    /// ModLockPost.locked
    public var isLocked: Bool
    /// ModLockPost.when_
    public var when: String

    public init(id: Double, modPersonID: Double, postID: Double, isLocked: Bool, when: String) {
        self.id = id
        self.modPersonID = modPersonID
        self.postID = postID
        self.isLocked = isLocked
        self.when = when
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Double.self, forKey: "id")
        self.modPersonID = try values.decode(Double.self, forKey: "mod_person_id")
        self.postID = try values.decode(Double.self, forKey: "post_id")
        self.isLocked = try values.decode(Bool.self, forKey: "locked")
        self.when = try values.decode(String.self, forKey: "when_")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(modPersonID, forKey: "mod_person_id")
        try values.encode(postID, forKey: "post_id")
        try values.encode(isLocked, forKey: "locked")
        try values.encode(when, forKey: "when_")
    }
}
