// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ModRemoveCommunityView: Codable {
    public var modRemoveCommunity: ModRemoveCommunity
    /// Person
    public var moderator: Person?
    public var community: Community

    public init(modRemoveCommunity: ModRemoveCommunity, moderator: Person? = nil, community: Community) {
        self.modRemoveCommunity = modRemoveCommunity
        self.moderator = moderator
        self.community = community
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.modRemoveCommunity = try values.decode(ModRemoveCommunity.self, forKey: "mod_remove_community")
        self.moderator = try values.decodeIfPresent(Person.self, forKey: "moderator")
        self.community = try values.decode(Community.self, forKey: "community")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(modRemoveCommunity, forKey: "mod_remove_community")
        try values.encodeIfPresent(moderator, forKey: "moderator")
        try values.encode(community, forKey: "community")
    }
}
