// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ModRemoveCommunity: Codable {
    /// ModRemoveCommunity.id
    public var id: Double
    /// PersonId
    public var modPersonID: Double
    public var communityID: Double
    /// ModRemoveCommunity.reason
    public var reason: String?
    /// ModRemoveCommunity.removed
    public var isRemoved: Bool
    /// ModRemoveCommunity.expires
    public var expires: String?
    /// ModRemoveCommunity.when_
    public var when: String

    public init(id: Double, modPersonID: Double, communityID: Double, reason: String? = nil, isRemoved: Bool, expires: String? = nil, when: String) {
        self.id = id
        self.modPersonID = modPersonID
        self.communityID = communityID
        self.reason = reason
        self.isRemoved = isRemoved
        self.expires = expires
        self.when = when
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Double.self, forKey: "id")
        self.modPersonID = try values.decode(Double.self, forKey: "mod_person_id")
        self.communityID = try values.decode(Double.self, forKey: "community_id")
        self.reason = try values.decodeIfPresent(String.self, forKey: "reason")
        self.isRemoved = try values.decode(Bool.self, forKey: "removed")
        self.expires = try values.decodeIfPresent(String.self, forKey: "expires")
        self.when = try values.decode(String.self, forKey: "when_")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(modPersonID, forKey: "mod_person_id")
        try values.encode(communityID, forKey: "community_id")
        try values.encodeIfPresent(reason, forKey: "reason")
        try values.encode(isRemoved, forKey: "removed")
        try values.encodeIfPresent(expires, forKey: "expires")
        try values.encode(when, forKey: "when_")
    }
}
