// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PasswordReset: Codable {
    /// PasswordReset.email
    public var email: String

    public init(email: String) {
        self.email = email
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.email = try values.decode(String.self, forKey: "email")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(email, forKey: "email")
    }
}
