// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PasswordChangeAfterReset: Codable {
    /// PasswordChangeAfterReset.token
    public var token: String
    /// PasswordChangeAfterReset.password
    public var password: String
    /// PasswordChangeAfterReset.password_verify
    public var passwordVerify: String

    public init(token: String, password: String, passwordVerify: String) {
        self.token = token
        self.password = password
        self.passwordVerify = passwordVerify
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.token = try values.decode(String.self, forKey: "token")
        self.password = try values.decode(String.self, forKey: "password")
        self.passwordVerify = try values.decode(String.self, forKey: "password_verify")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(token, forKey: "token")
        try values.encode(password, forKey: "password")
        try values.encode(passwordVerify, forKey: "password_verify")
    }
}
