// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PersonMentionResponse: Codable {
    public var personMentionView: PersonMentionView

    public init(personMentionView: PersonMentionView) {
        self.personMentionView = personMentionView
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.personMentionView = try values.decode(PersonMentionView.self, forKey: "person_mention_view")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(personMentionView, forKey: "person_mention_view")
    }
}
