// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PostReportResponse: Codable {
    public var postReportView: PostReportView

    public init(postReportView: PostReportView) {
        self.postReportView = postReportView
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.postReportView = try values.decode(PostReportView.self, forKey: "post_report_view")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(postReportView, forKey: "post_report_view")
    }
}
