// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public enum PostFeatureType: String, Codable, CaseIterable {
    case local = "Local"
    case community = "Community"
}
