// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PostReport: Codable {
    /// PostReportId
    public var id: Double
    /// PersonId
    public var creatorID: Double
    public var postID: Double
    /// PostReport.original_post_name
    public var originalPostName: String
    /// PostReport.original_post_url
    public var originalPostURL: String?
    /// PostReport.original_post_body
    public var originalPostBody: String?
    /// PostReport.reason
    public var reason: String
    /// PostReport.resolved
    public var isResolved: Bool
    /// PersonId
    public var resolverID: Double?
    /// PostReport.published
    public var published: String
    /// PostReport.updated
    public var updated: String?

    public init(id: Double, creatorID: Double, postID: Double, originalPostName: String, originalPostURL: String? = nil, originalPostBody: String? = nil, reason: String, isResolved: Bool, resolverID: Double? = nil, published: String, updated: String? = nil) {
        self.id = id
        self.creatorID = creatorID
        self.postID = postID
        self.originalPostName = originalPostName
        self.originalPostURL = originalPostURL
        self.originalPostBody = originalPostBody
        self.reason = reason
        self.isResolved = isResolved
        self.resolverID = resolverID
        self.published = published
        self.updated = updated
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Double.self, forKey: "id")
        self.creatorID = try values.decode(Double.self, forKey: "creator_id")
        self.postID = try values.decode(Double.self, forKey: "post_id")
        self.originalPostName = try values.decode(String.self, forKey: "original_post_name")
        self.originalPostURL = try values.decodeIfPresent(String.self, forKey: "original_post_url")
        self.originalPostBody = try values.decodeIfPresent(String.self, forKey: "original_post_body")
        self.reason = try values.decode(String.self, forKey: "reason")
        self.isResolved = try values.decode(Bool.self, forKey: "resolved")
        self.resolverID = try values.decodeIfPresent(Double.self, forKey: "resolver_id")
        self.published = try values.decode(String.self, forKey: "published")
        self.updated = try values.decodeIfPresent(String.self, forKey: "updated")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(creatorID, forKey: "creator_id")
        try values.encode(postID, forKey: "post_id")
        try values.encode(originalPostName, forKey: "original_post_name")
        try values.encodeIfPresent(originalPostURL, forKey: "original_post_url")
        try values.encodeIfPresent(originalPostBody, forKey: "original_post_body")
        try values.encode(reason, forKey: "reason")
        try values.encode(isResolved, forKey: "resolved")
        try values.encodeIfPresent(resolverID, forKey: "resolver_id")
        try values.encode(published, forKey: "published")
        try values.encodeIfPresent(updated, forKey: "updated")
    }
}
