// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PostView: Codable {
    public var post: Post
    /// Person
    public var creator: Person
    public var community: Community
    /// PostView.creator_banned_from_community
    public var isCreatorBannedFromCommunity: Bool
    /// PostAggregates
    public var counts: PostAggregates
    /// SubscribedType
    public var subscribed: SubscribedType
    /// PostView.saved
    public var isSaved: Bool
    /// PostView.read
    public var isRead: Bool
    /// PostView.creator_blocked
    public var isCreatorBlocked: Bool
    /// PostView.my_vote
    public var myVote: Double?
    /// PostView.unread_comments
    public var unreadComments: Double

    public init(post: Post, creator: Person, community: Community, isCreatorBannedFromCommunity: Bool, counts: PostAggregates, subscribed: SubscribedType, isSaved: Bool, isRead: Bool, isCreatorBlocked: Bool, myVote: Double? = nil, unreadComments: Double) {
        self.post = post
        self.creator = creator
        self.community = community
        self.isCreatorBannedFromCommunity = isCreatorBannedFromCommunity
        self.counts = counts
        self.subscribed = subscribed
        self.isSaved = isSaved
        self.isRead = isRead
        self.isCreatorBlocked = isCreatorBlocked
        self.myVote = myVote
        self.unreadComments = unreadComments
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.post = try values.decode(Post.self, forKey: "post")
        self.creator = try values.decode(Person.self, forKey: "creator")
        self.community = try values.decode(Community.self, forKey: "community")
        self.isCreatorBannedFromCommunity = try values.decode(Bool.self, forKey: "creator_banned_from_community")
        self.counts = try values.decode(PostAggregates.self, forKey: "counts")
        self.subscribed = try values.decode(SubscribedType.self, forKey: "subscribed")
        self.isSaved = try values.decode(Bool.self, forKey: "saved")
        self.isRead = try values.decode(Bool.self, forKey: "read")
        self.isCreatorBlocked = try values.decode(Bool.self, forKey: "creator_blocked")
        self.myVote = try values.decodeIfPresent(Double.self, forKey: "my_vote")
        self.unreadComments = try values.decode(Double.self, forKey: "unread_comments")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(post, forKey: "post")
        try values.encode(creator, forKey: "creator")
        try values.encode(community, forKey: "community")
        try values.encode(isCreatorBannedFromCommunity, forKey: "creator_banned_from_community")
        try values.encode(counts, forKey: "counts")
        try values.encode(subscribed, forKey: "subscribed")
        try values.encode(isSaved, forKey: "saved")
        try values.encode(isRead, forKey: "read")
        try values.encode(isCreatorBlocked, forKey: "creator_blocked")
        try values.encodeIfPresent(myVote, forKey: "my_vote")
        try values.encode(unreadComments, forKey: "unread_comments")
    }
}
