// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PostResponse: Codable {
    public var postView: PostView

    public init(postView: PostView) {
        self.postView = postView
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.postView = try values.decode(PostView.self, forKey: "post_view")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(postView, forKey: "post_view")
    }
}
