// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PrivateMessageResponse: Codable {
    public var privateMessageView: PrivateMessageView

    public init(privateMessageView: PrivateMessageView) {
        self.privateMessageView = privateMessageView
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.privateMessageView = try values.decode(PrivateMessageView.self, forKey: "private_message_view")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(privateMessageView, forKey: "private_message_view")
    }
}
