// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PrivateMessageView: Codable {
    public var privateMessage: PrivateMessage
    /// Person
    public var creator: Person
    /// Person
    public var recipient: Person

    public init(privateMessage: PrivateMessage, creator: Person, recipient: Person) {
        self.privateMessage = privateMessage
        self.creator = creator
        self.recipient = recipient
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.privateMessage = try values.decode(PrivateMessage.self, forKey: "private_message")
        self.creator = try values.decode(Person.self, forKey: "creator")
        self.recipient = try values.decode(Person.self, forKey: "recipient")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(privateMessage, forKey: "private_message")
        try values.encode(creator, forKey: "creator")
        try values.encode(recipient, forKey: "recipient")
    }
}
