// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PrivateMessageReportResponse: Codable {
    public var privateMessageReportView: PrivateMessageReportView

    public init(privateMessageReportView: PrivateMessageReportView) {
        self.privateMessageReportView = privateMessageReportView
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.privateMessageReportView = try values.decode(PrivateMessageReportView.self, forKey: "private_message_report_view")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(privateMessageReportView, forKey: "private_message_report_view")
    }
}
