// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PrivateMessagesResponse: Codable {
    /// PrivateMessagesResponse.private_messages
    public var privateMessages: [PrivateMessageView]

    public init(privateMessages: [PrivateMessageView]) {
        self.privateMessages = privateMessages
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.privateMessages = try values.decode([PrivateMessageView].self, forKey: "private_messages")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(privateMessages, forKey: "private_messages")
    }
}
