// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PurgeCommunity: Codable {
    public var communityID: Double
    /// PurgeCommunity.reason
    public var reason: String?
    /// PurgeCommunity.auth
    public var auth: String

    public init(communityID: Double, reason: String? = nil, auth: String) {
        self.communityID = communityID
        self.reason = reason
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.communityID = try values.decode(Double.self, forKey: "community_id")
        self.reason = try values.decodeIfPresent(String.self, forKey: "reason")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(communityID, forKey: "community_id")
        try values.encodeIfPresent(reason, forKey: "reason")
        try values.encode(auth, forKey: "auth")
    }
}
