// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public enum RegistrationMode: String, Codable, CaseIterable {
    case closed = "Closed"
    case requireApplication = "RequireApplication"
    case `open` = "Open"
}
