// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct RegistrationApplicationView: Codable {
    public var registrationApplication: RegistrationApplication
    /// LocalUser
    public var creatorLocalUser: LocalUser
    /// Person
    public var creator: Person
    /// Person
    public var admin: Person?

    public init(registrationApplication: RegistrationApplication, creatorLocalUser: LocalUser, creator: Person, admin: Person? = nil) {
        self.registrationApplication = registrationApplication
        self.creatorLocalUser = creatorLocalUser
        self.creator = creator
        self.admin = admin
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.registrationApplication = try values.decode(RegistrationApplication.self, forKey: "registration_application")
        self.creatorLocalUser = try values.decode(LocalUser.self, forKey: "creator_local_user")
        self.creator = try values.decode(Person.self, forKey: "creator")
        self.admin = try values.decodeIfPresent(Person.self, forKey: "admin")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(registrationApplication, forKey: "registration_application")
        try values.encode(creatorLocalUser, forKey: "creator_local_user")
        try values.encode(creator, forKey: "creator")
        try values.encodeIfPresent(admin, forKey: "admin")
    }
}
