// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct RemoveComment: Codable {
    public var commentID: Double
    /// RemoveComment.removed
    public var isRemoved: Bool
    /// RemoveComment.reason
    public var reason: String?
    /// RemoveComment.auth
    public var auth: String

    public init(commentID: Double, isRemoved: Bool, reason: String? = nil, auth: String) {
        self.commentID = commentID
        self.isRemoved = isRemoved
        self.reason = reason
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.commentID = try values.decode(Double.self, forKey: "comment_id")
        self.isRemoved = try values.decode(Bool.self, forKey: "removed")
        self.reason = try values.decodeIfPresent(String.self, forKey: "reason")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(commentID, forKey: "comment_id")
        try values.encode(isRemoved, forKey: "removed")
        try values.encodeIfPresent(reason, forKey: "reason")
        try values.encode(auth, forKey: "auth")
    }
}
