// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ResolvePostReport: Codable {
    /// PostReportId
    public var reportID: Double
    /// ResolvePostReport.resolved
    public var isResolved: Bool
    /// ResolvePostReport.auth
    public var auth: String

    public init(reportID: Double, isResolved: Bool, auth: String) {
        self.reportID = reportID
        self.isResolved = isResolved
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.reportID = try values.decode(Double.self, forKey: "report_id")
        self.isResolved = try values.decode(Bool.self, forKey: "resolved")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(reportID, forKey: "report_id")
        try values.encode(isResolved, forKey: "resolved")
        try values.encode(auth, forKey: "auth")
    }
}
