// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ResolveObject: Codable {
    /// ResolveObject.q
    public var q: String
    /// ResolveObject.auth
    public var auth: String

    public init(q: String, auth: String) {
        self.q = q
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.q = try values.decode(String.self, forKey: "q")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(q, forKey: "q")
        try values.encode(auth, forKey: "auth")
    }
}
