// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct SaveComment: Codable {
    public var commentID: Double
    /// SaveComment.save
    public var isSave: Bool
    /// SaveComment.auth
    public var auth: String

    public init(commentID: Double, isSave: Bool, auth: String) {
        self.commentID = commentID
        self.isSave = isSave
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.commentID = try values.decode(Double.self, forKey: "comment_id")
        self.isSave = try values.decode(Bool.self, forKey: "save")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(commentID, forKey: "comment_id")
        try values.encode(isSave, forKey: "save")
        try values.encode(auth, forKey: "auth")
    }
}
