// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct SavePost: Codable {
    public var postID: Double
    /// SavePost.save
    public var isSave: Bool
    /// SavePost.auth
    public var auth: String

    public init(postID: Double, isSave: Bool, auth: String) {
        self.postID = postID
        self.isSave = isSave
        self.auth = auth
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.postID = try values.decode(Double.self, forKey: "post_id")
        self.isSave = try values.decode(Bool.self, forKey: "save")
        self.auth = try values.decode(String.self, forKey: "auth")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(postID, forKey: "post_id")
        try values.encode(isSave, forKey: "save")
        try values.encode(auth, forKey: "auth")
    }
}
