// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public enum SearchType: String, Codable, CaseIterable {
    case all = "All"
    case comments = "Comments"
    case posts = "Posts"
    case communities = "Communities"
    case users = "Users"
    case url = "Url"
}
