// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct SearchResponse: Codable {
    /// SearchType
    public var type: SearchType
    /// SearchResponse.comments
    public var comments: [CommentView]
    /// SearchResponse.posts
    public var posts: [PostView]
    /// SearchResponse.communities
    public var communities: [CommunityView]
    /// SearchResponse.users
    public var users: [PersonView]

    public init(type: SearchType, comments: [CommentView], posts: [PostView], communities: [CommunityView], users: [PersonView]) {
        self.type = type
        self.comments = comments
        self.posts = posts
        self.communities = communities
        self.users = users
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.type = try values.decode(SearchType.self, forKey: "type_")
        self.comments = try values.decode([CommentView].self, forKey: "comments")
        self.posts = try values.decode([PostView].self, forKey: "posts")
        self.communities = try values.decode([CommunityView].self, forKey: "communities")
        self.users = try values.decode([PersonView].self, forKey: "users")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(type, forKey: "type_")
        try values.encode(comments, forKey: "comments")
        try values.encode(posts, forKey: "posts")
        try values.encode(communities, forKey: "communities")
        try values.encode(users, forKey: "users")
    }
}
