// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct SiteMetadata: Codable {
    /// SiteMetadata.title
    public var title: String?
    /// SiteMetadata.description
    public var description: String?
    /// SiteMetadata.image
    public var image: String?
    /// SiteMetadata.embed_video_url
    public var embedVideoURL: String?

    public init(title: String? = nil, description: String? = nil, image: String? = nil, embedVideoURL: String? = nil) {
        self.title = title
        self.description = description
        self.image = image
        self.embedVideoURL = embedVideoURL
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.title = try values.decodeIfPresent(String.self, forKey: "title")
        self.description = try values.decodeIfPresent(String.self, forKey: "description")
        self.image = try values.decodeIfPresent(String.self, forKey: "image")
        self.embedVideoURL = try values.decodeIfPresent(String.self, forKey: "embed_video_url")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(title, forKey: "title")
        try values.encodeIfPresent(description, forKey: "description")
        try values.encodeIfPresent(image, forKey: "image")
        try values.encodeIfPresent(embedVideoURL, forKey: "embed_video_url")
    }
}
