// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct SiteResponse: Codable {
    public var siteView: SiteView
    /// SiteResponse.taglines
    public var taglines: [Tagline]

    public init(siteView: SiteView, taglines: [Tagline]) {
        self.siteView = siteView
        self.taglines = taglines
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.siteView = try values.decode(SiteView.self, forKey: "site_view")
        self.taglines = try values.decode([Tagline].self, forKey: "taglines")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(siteView, forKey: "site_view")
        try values.encode(taglines, forKey: "taglines")
    }
}
