// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct SiteAggregates: Codable {
    /// SiteAggregates.id
    public var id: Double
    public var siteID: Double
    /// SiteAggregates.users
    public var users: Double
    /// SiteAggregates.posts
    public var posts: Double
    /// SiteAggregates.comments
    public var comments: Double
    /// SiteAggregates.communities
    public var communities: Double
    /// SiteAggregates.users_active_day
    public var usersActiveDay: Double
    /// SiteAggregates.users_active_week
    public var usersActiveWeek: Double
    /// SiteAggregates.users_active_month
    public var usersActiveMonth: Double
    /// SiteAggregates.users_active_half_year
    public var usersActiveHalfYear: Double

    public init(id: Double, siteID: Double, users: Double, posts: Double, comments: Double, communities: Double, usersActiveDay: Double, usersActiveWeek: Double, usersActiveMonth: Double, usersActiveHalfYear: Double) {
        self.id = id
        self.siteID = siteID
        self.users = users
        self.posts = posts
        self.comments = comments
        self.communities = communities
        self.usersActiveDay = usersActiveDay
        self.usersActiveWeek = usersActiveWeek
        self.usersActiveMonth = usersActiveMonth
        self.usersActiveHalfYear = usersActiveHalfYear
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(Double.self, forKey: "id")
        self.siteID = try values.decode(Double.self, forKey: "site_id")
        self.users = try values.decode(Double.self, forKey: "users")
        self.posts = try values.decode(Double.self, forKey: "posts")
        self.comments = try values.decode(Double.self, forKey: "comments")
        self.communities = try values.decode(Double.self, forKey: "communities")
        self.usersActiveDay = try values.decode(Double.self, forKey: "users_active_day")
        self.usersActiveWeek = try values.decode(Double.self, forKey: "users_active_week")
        self.usersActiveMonth = try values.decode(Double.self, forKey: "users_active_month")
        self.usersActiveHalfYear = try values.decode(Double.self, forKey: "users_active_half_year")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(siteID, forKey: "site_id")
        try values.encode(users, forKey: "users")
        try values.encode(posts, forKey: "posts")
        try values.encode(comments, forKey: "comments")
        try values.encode(communities, forKey: "communities")
        try values.encode(usersActiveDay, forKey: "users_active_day")
        try values.encode(usersActiveWeek, forKey: "users_active_week")
        try values.encode(usersActiveMonth, forKey: "users_active_month")
        try values.encode(usersActiveHalfYear, forKey: "users_active_half_year")
    }
}
