// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public enum SubscribedType: String, Codable, CaseIterable {
    case subscribed = "Subscribed"
    case notSubscribed = "NotSubscribed"
    case pending = "Pending"
}
